from fastapi import FastAPI
from .database import create_tables
from .models import User, Picture
# The title parameter you pass to FastAPI() is simply API metadata—specifically, 
# it becomes the “title” shown in your autogenerated OpenAPI docs (Swagger UI, Redoc, etc.
app = FastAPI()
create_tables()


